# Generated by Django 5.1.7 on 2025-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page', models.TextField()),
                ('movie_name', models.CharField(max_length=255)),
                ('genres', models.TextField()),
                ('overview', models.TextField()),
                ('Cast', models.TextField()),
                ('original_language', models.CharField(max_length=2)),
                ('storyline', models.TextField()),
                ('production_company', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.BigIntegerField()),
                ('budget_usd', models.BigIntegerField()),
                ('revenue_usd', models.BigIntegerField()),
                ('run_time_minutes', models.IntegerField()),
                ('release_country', models.CharField(max_length=255)),
                ('poster_url', models.TextField()),
                ('media_type', models.TextField(default='none')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
